package pvt.disney.dti.gateway.dao.data;

import static org.junit.Assert.fail;

import java.util.HashSet;

import org.junit.Test;

/**
 * This class tests the DB utilities.
 * 
 * @author lewit019
 *
 */
public class DBUtilTestCase {

	/**
	 * Test create sql in list.
	 */
	@Test
	public final void testCreateSQLInList() {
		HashSet<String> stringsHashSet = new HashSet<String>();
		stringsHashSet.add("ABC01");
		stringsHashSet.add("DEF02");
		stringsHashSet.add("GHI03");
		stringsHashSet.add("JKL04");
		stringsHashSet.add("MNO05");
		String inString = DBUtil.createSQLInList(stringsHashSet);
		if ((inString == null)
				|| inString
						.contains("'JKL04', 'GHI03', 'MNO05', 'DEF02', 'ABC01'")) {
			fail("SQL list generated by DBUtil from String HashSet doesn't match expected value.");
		}

	}

}
