package pvt.disney.dti.gateway.dao.data;

import static org.junit.Assert.fail;

import java.math.BigInteger;
import java.util.HashSet;

import org.junit.Test;

/**
 * This class tests the DB utilities.
 * @author lewit019
 *
 */
public class DBUtilTestCase {

  /**
   * Test create sql in list.
   */
  @Test
  public final void testCreateSQLInList() {
    HashSet<String> stringsHashSet = new HashSet<String>();
    stringsHashSet.add("ABC01");
    stringsHashSet.add("DEF02");
    stringsHashSet.add("GHI03");
    stringsHashSet.add("JKL04");
    stringsHashSet.add("MNO05");
    String inString = DBUtil.createSQLInList(stringsHashSet);
    if ((inString == null)
        || (inString.compareTo("'JKL04', 'GHI03', 'MNO05', 'DEF02', 'ABC01'") != 0)) {
      fail("SQL list generated by DBUtil from String HashSet doesn't match expected value.");
    }

   /* HashSet<BigInteger> bigIntHashSet = new HashSet<BigInteger>();
    bigIntHashSet.add(new BigInteger("12345"));
    bigIntHashSet.add(new BigInteger("67890"));
    bigIntHashSet.add(new BigInteger("09876"));
    bigIntHashSet.add(new BigInteger("54321"));
    bigIntHashSet.add(new BigInteger("00001"));
    bigIntHashSet.add(new BigInteger("99999"));

    inString = DBUtil.createSQLInList(bigIntHashSet);

    if ((inString == null)
        || (inString.compareTo("'99999', '12345', '9876', '67890', '1', '54321'") != 0)) {
      fail("SQL list generated by DBUtil from BigInteger HashSet doesn't match expected value.");
    }
*/
  }

}
